# Generated by Django 5.0.14 on 2026-06-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_mhz', models.FloatField()),
                ('distance_km', models.FloatField()),
                ('tx_power_dbm', models.FloatField()),
                ('tx_antenna_gain_dbi', models.FloatField()),
                ('rx_antenna_gain_dbi', models.FloatField()),
                ('tx_cable_loss_db', models.FloatField()),
                ('rx_cable_loss_db', models.FloatField()),
                ('rx_sensitivity_dbm', models.FloatField()),
                ('height_tx_m', models.FloatField(blank=True, null=True)),
                ('height_rx_m', models.FloatField(blank=True, null=True)),
                ('fspl_db', models.FloatField()),
                ('received_power_dbm', models.FloatField()),
                ('link_margin_db', models.FloatField()),
                ('classification_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Simulation',
                'verbose_name_plural': 'Simulations',
                'ordering': ['-created_at'],
            },
        ),
    ]
